### ISSUE TITLE
noany() function problem

### ISSUE THREAD

**Issue by Mark12870** [flowup/api-client-generator#98]
While the property doesn't have type. Swagger example:
```
Model:
    type: object
    properties:
      metadata: {}
```
(According to https://editor.swagger.io/ it is valid syntax.)

The generator will generate in `guards/index.ts` this line of code:
```
    // metadata?: any
    ( typeof arg.metadata === 'undefined' || isany(arg.metadata) ) &&
```
But the function `isany()` doesn't exists.
